### ISSUE TITLE
CKAN timeout when showcase plugin enabled

### ISSUE THREAD

**Issue by tremblaysimon** [ckan/ckanext-showcase#22] opened 2015-11-13 19:28 UTC
Hi, 

After enabled ckan showcase plugin (added showcase in production.ini file), the ckan instance doesn't respond anymore and timeout. Here some log output from apache: 

```
DEBUG [ckanext.showcase.model] ShowcasePackageAssociation table defined in memory

Script timed out before returning headers: apache.wsgi, referer: http://www.example.com/data/
```

Maybe it's something related with memory allocation in apache and wsgi?

**Comment by m-sinclair** [comment] 2016-02-05 00:50
+1 

nginx error.log
2016/02/05 00:45:27 [error] 1039#0: *211 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 173.183.78.81, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8080/"

**Comment by metaodi** [comment] 2016-05-10 15:44
Any further information about this?

**Comment by TkTech** [comment] 2016-05-10 17:25
Can you try running it with paster in debug mode and see if you can reproduce the timeout?

**Comment by metaodi** [comment] 2016-05-13 14:54
@TkTech I tried with `paster serve` and got the same result, the log message was `ShowcasePackageAssociation table defined in memory`.

This got me thinking: if this is the last log message, something has to be wrong with the database, as it should clearly create the tables and log this as well. I checked postgres and finally found the problem: there are two transactions open in Postgres, and the transaction opened by ckanext-showcase was blocked by an already existing transaction.
So the transaction basically waits forever and thus there is a timeout.

After digging a bit further I found out that the open transaction was accessing harvest* tables.

**The simple fix for this is to disable other plugins when running ckanext-showcase for the first time**, so it can create the table and properly initialize itself. Once that's done, the other plugins can be enabled again and everything works like a charm.

Note: to disable a plugin, remove it from the list of plugins in your config file, so that in the end it looks like this: `ckan.plugins = showcase`

I don't know if there is a way around this behavior, but it should probably be mentioned in the README somewhere.

**Comment by brew** [comment] 2016-05-13 17:51
This sounds very much like this issue being discussed in ideas-and-roadmap: https://github.com/ckan/ideas-and-roadmap/issues/164

One suggested solution would be to change showcase to stop the practise of auto-migrating, and instead have an explicit `init` command called as part of deployment.

**Comment by metaodi** [comment] 2016-05-13 17:59
@brew yes exactly. I'd support that. This kind of error is hard to debug and easily missed when you develop on a"standalone" CKAN instance.

This extensions provides a migration command for the related items, so the concept has already been applied for another use case.

**Closed** 2023-12-23 11:13 UTC
