### ISSUE TITLE
Tests broken

### ISSUE THREAD

**Issue by davidread** [ckan/ckanext-showcase#17] opened 2015-09-04 10:45 UTC
Travis says there are 4 tests broken, all with errors like this one:
```
======================================================================
ERROR: ckanext.showcase.tests.test_helpers.TestGetSiteStatistics.test_dataset_count_no_datasets
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/ckan/ckanext-showcase/ckanext/showcase/tests/test_helpers.py", line 15, in test_dataset_count_no_datasets
    stats = showcase_helpers.get_site_statistics()
  File "/home/travis/build/ckan/ckanext-showcase/ckanext/showcase/logic/helpers.py", line 22, in get_site_statistics
    {}, {"rows": 1, 'fq': 'dataset_type:showcase'})['count']
  File "/home/travis/build/ckan/ckanext-showcase/ckan/ckan/logic/__init__.py", line 416, in wrapped
    result = _action(context, data_dict, **kw)
  File "/home/travis/build/ckan/ckanext-showcase/ckan/ckan/logic/action/get.py", line 1825, in package_search
    user = context['user']
KeyError: 'user'
```

**Comment by brew** [comment] 2015-09-04 10:55
Thanks, this is a duplicate of #15.

**Closed by brew** 2015-09-04 10:55 UTC
